#pragma once

#include <process.h>


namespace Client
{
	const unsigned int g_iWinSizeX = { 1280 };
	const unsigned int g_iWinSizeY = { 720 };

	enum LEVELID { LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_HOME, LAST };

	enum class DIRECTION { XM, ZM, XP, ZP, XMZP, XPZP, XMZM, XPZM, YP,YM,LAST };
	enum class EVENT_ID { CREATE_OBJ, DEAD_OBJ, LEVEL_CHANGE, LAST };
#define DIR_WS DIRECTION::XM
#define DIR_EN DIRECTION::XP
#define DIR_WN DIRECTION::ZP
#define DIR_ES DIRECTION::ZM
#define DIR_W DIRECTION::XMZP
#define DIR_E DIRECTION::XPZM
#define DIR_N DIRECTION::XPZP
#define DIR_S DIRECTION::XMZM
#define DIR_D DIRECTION::YM
#define DIR_U DIRECTION::YP

	enum class ITEM_TYPE { 
		EQUIP , 
		DECO,
		CONSUMABLE , 
		BUILD , 
		ETC , 
		LAST 
	};

	NLOHMANN_JSON_SERIALIZE_ENUM(ITEM_TYPE, {
	{ITEM_TYPE::EQUIP, "EQUIP"},
	{ITEM_TYPE::DECO, "DECO"},
	{ITEM_TYPE::CONSUMABLE, "CONSUMABLE"},
	{ITEM_TYPE::BUILD, "BUILD"},
	{ITEM_TYPE::ETC, "ETC"},
	{ITEM_TYPE::LAST, "LAST"}
	});
	enum class ITEM_GRADE
	{
		NORMAL,
		ELITE,
		EXCELENT,
		LEGENDARY,
		MYTHIC,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(ITEM_GRADE, {
		{ITEM_GRADE::NORMAL, "NORMAL"},
		{ITEM_GRADE::ELITE, "ELITE"},
		{ITEM_GRADE::EXCELENT, "EXCELENT"},
		{ITEM_GRADE::LEGENDARY, "LEGENDARY"},
		{ITEM_GRADE::MYTHIC, "MYTHIC"},
		{ITEM_GRADE::LAST, "LAST"}
		});
#pragma region BUILD_ITEM

	enum class BUILD_ITEM_TYPE
	{
		BLOCK,
		FILED,
		PORTAL,
		SPAWN,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(BUILD_ITEM_TYPE, {
		{BUILD_ITEM_TYPE::BLOCK, "BLOCK"},
		{BUILD_ITEM_TYPE::FILED, "FILED"},
		{BUILD_ITEM_TYPE::PORTAL, "PORTAL"},
		{BUILD_ITEM_TYPE::SPAWN, "SPAWN"},
		{BUILD_ITEM_TYPE::LAST, "LAST"}
		});
	enum class BUILD_ITEM_ID
	{
		GRASS_1,
		ROCK_1,
		BUSH_1,
		FLOWER_1,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(BUILD_ITEM_ID, {
		{BUILD_ITEM_ID::GRASS_1, "GRASS_1"},
		{BUILD_ITEM_ID::ROCK_1, "ROCK_1"},
		{BUILD_ITEM_ID::BUSH_1, "BUSH_1"},
		{BUILD_ITEM_ID::FLOWER_1, "FLOWER_1"},
		{BUILD_ITEM_ID::LAST, "LAST"}
		});
#pragma endregion

	enum class EQUIP_ITEM_TYPE
	{
		HAT,
		TOP,
		BOTTOM,
		SUIT,
		GLOVES,
		SHOES,
		CAPE,
		WEAPON,
		EAR,

		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(EQUIP_ITEM_TYPE, {
	{EQUIP_ITEM_TYPE::HAT, "HAT"},
	{EQUIP_ITEM_TYPE::TOP, "TOP"},
	{EQUIP_ITEM_TYPE::BOTTOM, "BOTTOM"},
	{EQUIP_ITEM_TYPE::SUIT, "SUIT"},
	{EQUIP_ITEM_TYPE::GLOVES, "GLOVES"},
	{EQUIP_ITEM_TYPE::SHOES, "SHOES"},
	{EQUIP_ITEM_TYPE::CAPE, "CAPE"},
	{EQUIP_ITEM_TYPE::WEAPON, "WEAPON"},
	{EQUIP_ITEM_TYPE::EAR, "EAR"},
	{EQUIP_ITEM_TYPE::LAST, "LAST"}
		});
	enum class EQUIP_ITEM_ID
	{
		BASIC_SHOES,
		BASIC_SUIT,
		BASIC_HAT,
		BASIC_STAFF,
		EVILWINGS,

		FIREPRISM_CAPE, 
		FIREPRISM_EAR,
		FIREPRISM_SHOES,
		FIREPRISM_GLOVE,
		FIREPRISM_TOP,
		FIREPRISM_BOTTOM,
		FIREPRISM_HAT,
		FIREPRISM_STAFF, 
		LAST
	};

	NLOHMANN_JSON_SERIALIZE_ENUM(EQUIP_ITEM_ID, {
	{EQUIP_ITEM_ID::BASIC_SHOES, "BASIC_SHOEdS"},
	{EQUIP_ITEM_ID::BASIC_SUIT, "BASIC_SUIT"},
	{EQUIP_ITEM_ID::BASIC_HAT, "BASIC_HAT"},
	{EQUIP_ITEM_ID::BASIC_STAFF, "BASIC_STAFF"},
	{EQUIP_ITEM_ID::EVILWINGS, "EVILWINGS"},
	{EQUIP_ITEM_ID::FIREPRISM_CAPE, "FIREPRISM_CAPE"},
	{EQUIP_ITEM_ID::FIREPRISM_EAR, "FIREPRISM_EAR"},
	{EQUIP_ITEM_ID::FIREPRISM_SHOES, "FIREPRISM_SHOES"},
	{EQUIP_ITEM_ID::FIREPRISM_GLOVE, "FIREPRISM_GLOVE"},
	{EQUIP_ITEM_ID::FIREPRISM_TOP, "FIREPRISM_TOP"},
	{EQUIP_ITEM_ID::FIREPRISM_BOTTOM, "FIREPRISM_BOTTOM"},
	{EQUIP_ITEM_ID::FIREPRISM_HAT, "FIREPRISM_HAT"},
	{EQUIP_ITEM_ID::FIREPRISM_STAFF, "FIREPRISM_STAFF"},
	{EQUIP_ITEM_ID::LAST, "LAST"}
		});

	enum class DECO_TYPE
	{
		FACE,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(DECO_TYPE, {
		{DECO_TYPE::FACE, "FACEDECO"},
		{DECO_TYPE::LAST, "LAST"}
	});
	enum class CUSTOMIZE_PART
	{
		HAIR,
		FACE,
		SKIN,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(CUSTOMIZE_PART, {
		{CUSTOMIZE_PART::HAIR, "HAIR"},
		{CUSTOMIZE_PART::FACE, "FACE"},
		{CUSTOMIZE_PART::SKIN, "SKIN"},
		{CUSTOMIZE_PART::LAST, "LAST"}
	});

	typedef struct UIListItemData
	{

	}UIITEMDATA;

	enum class SKILL_TYPE
	{
		INSTANT,
		PASSIVE,
		CHANNELING,
		CHARGING,
		CASTING,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(SKILL_TYPE, {
		{SKILL_TYPE::INSTANT, "INSTANT"},
		{SKILL_TYPE::PASSIVE, "PASSIVE"},
		{SKILL_TYPE::CHANNELING, "CHANNELING"},
		{SKILL_TYPE::CHARGING, "CHARGING"},
		{SKILL_TYPE::CASTING, "CASTING"},
		{SKILL_TYPE::LAST, "LAST"}
	});
	enum class SKILL_ID
	{
		BASIC_ATTACK,
		MAGIC_CLAW,
		FLAME_WAVE,
		FIRE_TORNADO,
		KINDLING,
		KINDLING2,
		BBQ_PARTY,
		FAKE_METEOR,
		FLAME_BURST,
		WILD_FIRE,
		LAST
	};
	NLOHMANN_JSON_SERIALIZE_ENUM(SKILL_ID, {
		{SKILL_ID::BASIC_ATTACK, "BASIC_ATTACK"},
		{SKILL_ID::MAGIC_CLAW, "MAGIC_CLAW"},
		{SKILL_ID::FLAME_WAVE, "FLAME_WAVE"},
		{SKILL_ID::FIRE_TORNADO, "FIRE_TORNADO"},
		{SKILL_ID::KINDLING, "KINDLING"},
		{SKILL_ID::KINDLING2, "KINDLING2"},
		{SKILL_ID::BBQ_PARTY, "BBQ_PARTY"},
		{SKILL_ID::FAKE_METEOR, "FAKE_METEOR"},
		{SKILL_ID::FLAME_BURST, "FLAME_BURST"},
		{SKILL_ID::WILD_FIRE, "WILD_FIRE"},
		{SKILL_ID::LAST, "LAST"}
	});
	enum class SKILL_COST_TYPE
	{
		NONE,
		SP,
		STAMINA,
		LAST
	};

	NLOHMANN_JSON_SERIALIZE_ENUM(SKILL_COST_TYPE, {
		{SKILL_COST_TYPE::NONE, "NONE"},
		{SKILL_COST_TYPE::SP, "SP"},
		{SKILL_COST_TYPE::STAMINA, "STAMINA"},
		{SKILL_COST_TYPE::LAST, "LAST"}
	});



}

extern HINSTANCE g_hInst;
extern HWND g_hWnd;

using namespace Client;
